$schema: http://json-schema.org/draft-06/schema#
definitions:
  Product:
    description: 'Product(iprcode: int, cprcode: int, oprcode: Union[int, NoneType],
      pr_dpcode: Union[str, NoneType], pr_barcode: Union[str, NoneType], pr_barcode2:
      Union[str, NoneType], pr_sucode1: Union[str, NoneType], pr_suref3: Union[str,
      NoneType], pr_sa_method: Union[str, NoneType], sellingPrice: Union[int, NoneType])'
    properties:
      cprcode:
        type: integer
      iprcode:
        type: integer
      oprcode:
        type: integer
      pr_barcode:
        type: string
      pr_barcode2:
        type: string
      pr_dpcode:
        type: string
      pr_sa_method:
        type: string
      pr_sucode1:
        type: string
      pr_suref3:
        type: string
      sellingPrice:
        type: integer
      psqty:
        type: integer
      pr_country_en:
        type: string
      online_category_l1_en:
        type: string
      online_category_l2_en:
        type: string
      online_category_l3_en:
        type: string
      hema_brand_en:
        type: string
      hema_sizedesc:
        type: string
      hema_name_en:
        type: string
      hema_name_th:
        type: string
      ordertype:
        type: string
      pr_abb:
        type: string
      pr_active:
        type: boolean
      pr_cgcode:
        type: string
      pr_engname:
        type: string
      pr_ggcode:
        type: string
      pr_market:
        type: string
      pr_name:
        type: string
      prtype:
        type: string
        enum:
        - I
        - C
      pstype:
        type: string
        enum:
        - '1'
        - '2'
        - '3'
      pr_country_th:
        type: string
      pr_keyword_th:
        type: string
      pr_keyword_en:
        type: string
      pr_filter_th:
        type: string
      pr_filter_en:
        type: string
      online_category_l1_th:
        type: string
      online_category_l2_th:
        type: string
      online_category_l3_th:
        type: string
      villa_category_l1_en:
        type: string
      villa_category_l2_en:
        type: string
      villa_category_l3_en:
        type: string
      villa_category_l4_en:
        type: string
      content_en:
        type: string
      content_th:
        type: string
      hema_brand_th:
        type: string
      pr_brand_en:
        type: string
      pr_brand_th:
        type: string
      pr_online_name_en:
        type: string
      pr_online_name_th:
        type: string
      pr_name_en:
        type: string
      pr_name_th:
        type: string
      sort_weight:
        type: number
      master_online:
        type: boolean
      salemode_unit:
        type: string
      ba_nprice:
        type: number
      sort_villa_sku:
        type: number
      portion:
        type: string
      warehouse:
        type: integer
      consign_inv:
        type: integer
      enabled:
        type: boolean
      preorder_delivery_type:
        type: string
        enum:
        - fixed
        - relative
      preorder_fix_date:
        type: integer
      preorder_relative_day:
        type: integer
      product_detail_description:
        type: string
      meta_title:
        type: string
      meta_keyword:
        type: string
      meta_description:
        type: string
      height:
        type: number
      width:
        type: number
      depth:
        type: number
      weight:
        type: number
      priority_score:
        type: number
      avail_store:
        type: array
        items:
            type: string
      product_attribute_id:
        type: integer
      product_attribute:
        type: object
      related_products:
        type: array
        items:
            type: int  
        required:
        - iprcode
        - cprcode
        type: object
      shipping_type:
        type: string
        enum:
        - 'DRY'
        - 'FRESH'
        
description: 'ValueUpdate(items: List[__main__.Product])'
properties:
  items:
    items:
      $ref: '#/definitions/Product'
    type: array
required:
- items
type: object

